name: deploy
on:
  push:
    branches:
      - main
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
jobs:
  terraform:
    if: github.repository == 'np-complete/np-complete-infra'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
