name: test
on: pull_request
permissions:
  contents: read
  pull-requests: read
jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
      - run: tflint --init
      - run: tflint
